apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sj-5g6ft
resources:
  - ../../base
images:
  - name: ghcr.io/stu-10/nkp-track-field-demo
    newName: ghcr.io/stu-10/nkp-track-field-demo
    digest: sha256:769826ffb73455edcaaff18924f17cb53dc81729cbf09a8a7a348a09a06569d9
