apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sj-5g6ft
resources:
  - ../../base
images:
  - name: ghcr.io/stu-10/nkp-track-field-demo
    newName: ghcr.io/stu-10/nkp-track-field-demo
    digest: sha256:c9956fc2be32849386f1a63d108f1f0b4c567bf61ffa437350b0b0f77051b070
