apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-native-games
resources:
  - ../../base
  - namespace.yaml
images:
  - name: ghcr.io/replace-owner/cloud-native-games
    newName: ghcr.io/replace-owner/cloud-native-games
    newTag: bootstrap
